import React, { useState, useEffect } from 'react';
import { FileText, Download, Plus, CheckCircle, Clock } from 'lucide-react';
import { reportService } from '../services/reportService';
import { formatDate } from '../utils/formatters';

const Reports = () => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [reportTitle, setReportTitle] = useState('Executive Return Intelligence & Prevention Report');
  const [successMsg, setSuccessMsg] = useState('');

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    setLoading(true);
    try {
      const res = await reportService.getReports();
      if (res.success) setReports(res.data);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateReport = async (e) => {
    e.preventDefault();
    setGenerating(true);
    setSuccessMsg('');
    try {
      const res = await reportService.generateReport(reportTitle);
      if (res.success) {
        setSuccessMsg('PDF Report generated successfully using ReportLab!');
        fetchReports();
      }
    } catch (err) {
      console.error(err);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div>
      <div className="page-header">
        <div>
          <h1 className="page-title">Executive Management Reports</h1>
          <p className="page-subtitle">Generate downloadable ReportLab PDF reports compiling root cause analysis and financial savings</p>
        </div>
      </div>

      <div className="grid-2" style={{ marginBottom: '24px' }}>
        {/* Report Generator Card */}
        <div className="card">
          <div className="card-title">
            <FileText size={18} color="var(--primary)" /> Generate New PDF Report
          </div>

          <form onSubmit={handleGenerateReport}>
            <div className="form-group">
              <label className="form-label">Report Title</label>
              <input
                type="text"
                className="form-input"
                value={reportTitle}
                onChange={(e) => setReportTitle(e.target.value)}
                required
              />
            </div>

            {successMsg && (
              <div style={{ padding: '10px', background: '#ecfdf5', color: '#047857', border: '1px solid #a7f3d0', borderRadius: '6px', fontSize: '0.85rem', marginBottom: '12px' }}>
                <CheckCircle size={16} inline="true" /> {successMsg}
              </div>
            )}

            <button type="submit" disabled={generating} className="btn btn-primary" style={{ width: '100%', padding: '12px' }}>
              {generating ? 'Compiling PDF Report...' : 'Generate & Export PDF Report'}
            </button>
          </form>
        </div>

        {/* Report Info */}
        <div className="card" style={{ background: '#f8fafc' }}>
          <div className="card-title">Report Content & Included Analytics</div>
          <ul style={{ paddingLeft: '20px', fontSize: '0.875rem', color: '#475569', display: 'flex', flexDirection: 'column', gap: '8px' }}>
            <li>ASPIDA Official Header & Date stamp</li>
            <li>Executive Summary & Key KPIs</li>
            <li>Core Platform Performance Metrics Table</li>
            <li>High-Risk Product Portfolio Breakdown</li>
            <li>Strategic AI Recommendations & Savings Estimates</li>
          </ul>
        </div>
      </div>

      {/* Generated Reports Table */}
      <h2 style={{ fontSize: '1.1rem', fontWeight: 700, color: '#0f172a', marginBottom: '16px' }}>Available Generated Reports</h2>

      <div className="table-container">
        <table className="data-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Report Title</th>
              <th>Filename</th>
              <th>Generated By</th>
              <th>Date Created</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr><td colSpan={6} style={{ textAlign: 'center', padding: '30px' }}>Loading reports list...</td></tr>
            ) : reports.length === 0 ? (
              <tr><td colSpan={6} style={{ textAlign: 'center', padding: '30px', color: '#94a3b8' }}>No reports generated yet. Click above to generate your first PDF report.</td></tr>
            ) : (
              reports.map(r => (
                <tr key={r.id}>
                  <td style={{ fontWeight: 700, color: '#64748b' }}>#{r.id}</td>
                  <td style={{ fontWeight: 600, color: '#0f172a' }}>{r.title}</td>
                  <td style={{ fontSize: '0.8rem', color: '#64748b' }}>{r.filename}</td>
                  <td>{r.generated_by}</td>
                  <td>{formatDate(r.created_at)}</td>
                  <td>
                    <a
                      href={reportService.getDownloadUrl(r.filename)}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="btn btn-secondary"
                      style={{ padding: '4px 10px', fontSize: '0.75rem', textDecoration: 'none' }}
                    >
                      <Download size={14} /> Download PDF
                    </a>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default Reports;
